server:
  port: 5000

spring:
  mvc.view.prefix: /WEB-INF/view/
  mvc.view.suffix: .jsp

logging:
#  path: c:\temp\
  level:
    org.springframework.web: DEBUG
    com.spring: DEBUG

datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://ec2-107-22-192-11.compute-1.amazonaws.com:5432/d37nd8135gbtv1?sslmode=require
  username: bknuvzcktzakal
  password: c0a7b72496c991f02defe6062bf830a4d497fead3d056b5049d4eb0f5e755e04
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
